### ISSUE TITLE
Feature Request - Command Line Template / Archive Additions

### ISSUE THREAD

**Issue by SamChami** [wndrfl/wonderpress-cli#3]
Would it be possible to create a command line template / archive generator?
Example
```bash
$ wonderpress template campsite
 // template-campsite.php Created!
 // css/src/sheets/_campsite.scss Created!
 // Imported 'sheets/campsite' in css/src/styles.scss
```

Maybe even add a --js flag to add/import script with the same name?

**Comment by johnnietheblack** [comment]
This is a great idea. Work is in progress!

**Comment by johnnietheblack** [comment]
@SamChami the latest build includes a new command `wonderpress template create -n campsite` that creates a template-campsite.php and the corresponding static assets. 🎉
